db:
    image: "postgres"
    ports:
        - "5432:5432"-
web:
    build: .
    command: gunicorn --reload -b 0.0.0.0:5000 cinetify.app:api
    volumes:
        - .:/src
        - ./sql:/opt/flyway-3.2.1/sql
    ports:
        - "5000:5000"
    links:
        - db
    environment:
        SECRET_KEY: secretkey